FROM splatform/stratos-goose-base:dev

RUN zypper -n in postgresql mariadb-client
RUN go get github.com/go-sql-driver/mysql
COPY goose /usr/local/bin/
COPY deploy/db/dbconf.yml db/dbconf.yml
COPY deploy/db/migrations db/migrations
COPY deploy/db/scripts/run-postflight-job.k8s.sh /run-postflight-job.sh
CMD ["/run-postflight-job.sh"]
