FROM splatform/stratos-bk-base:opensuse

WORKDIR /src

COPY deploy/db/dbconf.yml db/dbconf.yml
COPY deploy/db/scripts/development.sh .
COPY deploy/db/scripts/wait-for-it.sh .
COPY outputs/portal-proxy .
RUN chmod +x portal-proxy
RUN chmod +x wait-for-it.sh
RUN chmod +x development.sh

CMD bash /src/wait-for-it.sh -t 90 mariadb:3306 && bash /src/development.sh
