/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .run(registerApi);

  registerApi.$inject = [
    '$http',
    'apiManager'
  ];

  function registerApi($http, apiManager) {
    apiManager.register('cloud-foundry.api.Files', new FilesApi($http));
  }

  function FilesApi($http) {
    this.$http = $http;
  }

  /* eslint-disable camelcase */
  angular.extend(FilesApi.prototype, {

   /*
    * Retrieve File
    * The endpoint does not function with Diego apps.
    * Please use CF CLI command `cf ssh` for Diego apps.
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/237/files/retrieve_file.html
    */
    RetrieveFile: function (app_guid, instance_index, file_path, params, httpConfigOptions) {
      var config = {};
      config.params = params;
      config.url = '/pp/v1/proxy/v2/apps/' + app_guid + '/instances/' + instance_index + '/files/' + file_path + '';
      config.method = 'GET';

      for (var option in httpConfigOptions) {
        if (!httpConfigOptions.hasOwnProperty(option)) { continue; }
        config[option] = httpConfigOptions[option];
      }
      return this.$http(config);
    }

  });
  /* eslint-enable camelcase */

})();
