/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .run(registerApi);

  registerApi.$inject = [
    '$http',
    'app.api.apiManager'
  ];

  function registerApi($http, apiManager) {
    apiManager.register('cloud-foundry.api.OrganizationQuotaDefinitions', new OrganizationQuotaDefinitionsApi($http));
  }

  function OrganizationQuotaDefinitionsApi($http) {
    this.$http = $http;
  }

  /* eslint-disable camelcase */
  angular.extend(OrganizationQuotaDefinitionsApi.prototype, {

   /*
    * Creating a Organization Quota Definition
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/237/organization_quota_definitions/creating_a_organization_quota_definition.html
    */
    CreateOrganizationQuotaDefinition: function (value, params, httpConfigOptions) {
      var config = {};
      config.params = params;
      config.url = '/pp/v1/proxy/v2/quota_definitions';
      config.method = 'POST';
      config.data = value;

      for (var option in httpConfigOptions) {
        if (!httpConfigOptions.hasOwnProperty(option)) { continue; }
        config[option] = httpConfigOptions[option];
      }
      return this.$http(config);
    },

   /*
    * Delete a Particular Organization Quota Definition
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/237/organization_quota_definitions/delete_a_particular_organization_quota_definition.html
    */
    DeleteOrganizationQuotaDefinition: function (guid, params, httpConfigOptions) {
      var config = {};
      config.params = params;
      config.url = '/pp/v1/proxy/v2/quota_definitions/' + guid + '';
      config.method = 'DELETE';

      for (var option in httpConfigOptions) {
        if (!httpConfigOptions.hasOwnProperty(option)) { continue; }
        config[option] = httpConfigOptions[option];
      }
      return this.$http(config);
    },

   /*
    * List all Organization Quota Definitions
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/237/organization_quota_definitions/list_all_organization_quota_definitions.html
    */
    ListAllOrganizationQuotaDefinitions: function (params, httpConfigOptions) {
      var config = {};
      config.params = params;
      config.url = '/pp/v1/proxy/v2/quota_definitions';
      config.method = 'GET';

      for (var option in httpConfigOptions) {
        if (!httpConfigOptions.hasOwnProperty(option)) { continue; }
        config[option] = httpConfigOptions[option];
      }
      return this.$http(config);
    },

   /*
    * Retrieve a Particular Organization Quota Definition
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/237/organization_quota_definitions/retrieve_a_particular_organization_quota_definition.html
    */
    RetrieveOrganizationQuotaDefinition: function (guid, params, httpConfigOptions) {
      var config = {};
      config.params = params;
      config.url = '/pp/v1/proxy/v2/quota_definitions/' + guid + '';
      config.method = 'GET';

      for (var option in httpConfigOptions) {
        if (!httpConfigOptions.hasOwnProperty(option)) { continue; }
        config[option] = httpConfigOptions[option];
      }
      return this.$http(config);
    },

   /*
    * Updating a Organization Quota Definition
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/237/organization_quota_definitions/updating_a_organization_quota_definition.html
    */
    UpdateOrganizationQuotaDefinition: function (guid, value, params, httpConfigOptions) {
      var config = {};
      config.params = params;
      config.url = '/pp/v1/proxy/v2/quota_definitions/' + guid + '';
      config.method = 'PUT';
      config.data = value;

      for (var option in httpConfigOptions) {
        if (!httpConfigOptions.hasOwnProperty(option)) { continue; }
        config[option] = httpConfigOptions[option];
      }
      return this.$http(config);
    }

  });
  /* eslint-enable camelcase */

})();
