FROM stackatotest/hsc-concourse-e2e:latest

# These args need to be consumed, otherwise build fails
ARG USER_ID
ARG GROUP_ID
ARG USER_NAME

WORKDIR /usr/src/app

CMD bash provision.sh && cd tools && xvfb-run --server-args='-screen 0 1280x1024x24' ./node_modules/.bin/protractor protractor.conf.js
