FROM ubuntu:14.04

RUN apt-get update && \
    apt-get install -y --reinstall ca-certificates ca-certificates-java && \
    mkdir -p /srv

WORKDIR /srv

COPY portal-proxy portal-proxy
COPY dev-certs dev-certs
COPY tools/wait/wait-for-it.sh tools/wait-for-it.sh

RUN chmod +x portal-proxy

EXPOSE 443

ENTRYPOINT ["bash", "tools/wait-for-it.sh", "postgres:5432", "--", "./portal-proxy"]
