FROM ubuntu:14.04

ENV DB_HOST="hsc-db" DB="postgres" DB_USER="stolon" \
  POSTGRES_USER="stolon" POSTGRES_PASSWORD="stolon" CFGDB_PORT=5432 \
  STRATOS_DB="stratos-db" STRATOS_USER="stratos" STRATOS_PWD="stratos" SQL="InitialSchema.sql"

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql

COPY /db/run.sh /
COPY /db/initial/InitialSchema.sql /

CMD ["/run.sh"]
