version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stratos-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: strat0s
      MYSQL_DATABASE: stratosdb
      MYSQL_USER: stratos
      MYSQL_PASSWORD: strat0s
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: