FROM ubuntu:14.04

RUN apt-get update && \
    apt-get install -y --reinstall ca-certificates ca-certificates-java && \
    mkdir -p /srv

WORKDIR /srv

COPY templates/ templates/
COPY portal-proxy portal-proxy
COPY /containers/proxy/run.sh /

RUN chmod +x portal-proxy
RUN chmod +x /run.sh

EXPOSE 443
CMD ["/run.sh"]
