FROM stackatotest/hsc-concourse:test

# These args need to be consumed, otherwise build fails
ARG USER_ID
ARG GROUP_ID
ARG USER_NAME

WORKDIR /usr/src/app
CMD bash e2e/provision.sh && cd tools && npm run headless-e2e -- --params.host=nginx --params.port=
