FROM node:6.9.1

ARG USER_ID
ARG GROUP_ID
ARG USER_NAME

# Run this as a normal with the specified ID
RUN groupadd -r -g ${GROUP_ID} ${USER_NAME} && useradd -m -r -g ${USER_NAME} -u ${USER_ID} ${USER_NAME}
USER ${USER_NAME}

WORKDIR /usr/src/app

CMD bash provision.sh && cd tools && node_modules/.bin/gulp watch
