/* DO NOT EDIT: This code has been generated by swagger-codegen */
(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .run(registerApi);

  registerApi.$inject = [
    '$http',
    'app.api.apiManager'
  ];

  function registerApi($http, apiManager) {
    apiManager.register('cloud-foundry.api.HceNotificationApi', new HceNotificationApi($http));
  }

  /**
    * @constructor
    * @name HceNotificationApi
    * @description For more information on this API, please see:
    * https://github.com/hpcloud/hce-rest-service/blob/master/app/v2/swagger.yml
    * @param {object} $http - the Angular $http service
    * @property {object} $http - the Angular $http service
    * @property {string} baseUrl - the API base URL
    * @property {object} defaultHeaders - the default headers
    */
  function HceNotificationApi($http) {
    this.$http = $http;
    this.baseUrl = '/api/ce/v2';
    this.defaultHeaders = {
      Accept: 'application/json',
      'Content-Type': 'application/json'
    };
  }

  angular.extend(HceNotificationApi.prototype, {
    /**
     * @name addNotificationTarget
     * @description Add a NotificationTarget (for a project).
     * @param {object} data - the request body
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    addNotificationTarget: function (data, params) {
      var path = this.baseUrl + '/notifications/targets';

      var config = {
        method: 'POST',
        url: path,
        params: params || {},
        data: data,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name getNotificationTarget
     * @description Get the specified notification target.
     * @param {!number} notificationTargetId - NotificationTarget id.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    getNotificationTarget: function (notificationTargetId, params) {
      var path = this.baseUrl + '/notifications/targets/{notification_target_id}'
        .replace('{' + 'notification_target_id' + '}', notificationTargetId);

      var config = {
        method: 'GET',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name getNotificationTargets
     * @description List notifiction targets, optionally filtering.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    getNotificationTargets: function (params) {
      var path = this.baseUrl + '/notifications/targets';

      var config = {
        method: 'GET',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name removeNotificationTarget
     * @description Remove the specified notification target.
     * @param {!number} notificationTargetId - NotificationTarget id.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    removeNotificationTarget: function (notificationTargetId, params) {
      var path = this.baseUrl + '/notifications/targets/{notification_target_id}'
        .replace('{' + 'notification_target_id' + '}', notificationTargetId);

      var config = {
        method: 'DELETE',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name updateNotificationTarget
     * @description Update the specified notification target.
     * @param {!number} notificationTargetId - NotificationTarget id.
     * @param {object} data - the request body
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    updateNotificationTarget: function (notificationTargetId, data, params) {
      var path = this.baseUrl + '/notifications/targets/{notification_target_id}'
        .replace('{' + 'notification_target_id' + '}', notificationTargetId);

      var config = {
        method: 'PUT',
        url: path,
        params: params || {},
        data: data,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    }
  });
})();
