/* DO NOT EDIT: This code has been generated by swagger-codegen */
(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .run(registerApi);

  registerApi.$inject = [
    '$http',
    'app.api.apiManager'
  ];

  function registerApi($http, apiManager) {
    apiManager.register('cloud-foundry.api.HceProjectApi', new HceProjectApi($http));
  }

  /**
    * @constructor
    * @name HceProjectApi
    * @description For more information on this API, please see:
    * https://github.com/hpcloud/hce-rest-service/blob/master/app/v2/swagger.yml
    * @param {object} $http - the Angular $http service
    * @property {object} $http - the Angular $http service
    * @property {string} baseUrl - the API base URL
    * @property {object} defaultHeaders - the default headers
    */
  function HceProjectApi($http) {
    this.$http = $http;
    this.baseUrl = '/api/ce/v2';
    this.defaultHeaders = {
      Accept: 'application/json',
      'Content-Type': 'application/json'
    };
  }

  angular.extend(HceProjectApi.prototype, {
    /**
     * @name addMember
     * @description Add a member (user) to a project.
     * @param {!number} projectId - The project id.
     * @param {object} data - the request body
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    addMember: function (projectId, data, params) {
      var path = this.baseUrl + '/projects/{project_id}/members'
        .replace('{' + 'project_id' + '}', projectId);

      var config = {
        method: 'POST',
        url: path,
        params: params || {},
        data: data,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name addPipelineTask
     * @description Add a pipeline task for a specific project.
     * @param {object} data - the request body
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    addPipelineTask: function (data, params) {
      var path = this.baseUrl + '/pipelines/tasks';

      var config = {
        method: 'POST',
        url: path,
        params: params || {},
        data: data,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name createProject
     * @description Create a new project.
     * @param {object} data - the request body
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    createProject: function (data, params) {
      var path = this.baseUrl + '/projects';

      var config = {
        method: 'POST',
        url: path,
        params: params || {},
        data: data,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name deleteProject
     * @description Delete the specified &#x60;Project&#x60; instance.\n
     * @param {!number} projectId - The id of the &#x60;Project&#x60; instance to delete.\n
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    deleteProject: function (projectId, params) {
      var path = this.baseUrl + '/projects/{project_id}'
        .replace('{' + 'project_id' + '}', projectId);

      var config = {
        method: 'DELETE',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name getPipelineTask
     * @description Get the specified pipeline task.
     * @param {!number} taskId - PipelineTask id.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    getPipelineTask: function (taskId, params) {
      var path = this.baseUrl + '/pipelines/tasks/{task_id}'
        .replace('{' + 'task_id' + '}', taskId);

      var config = {
        method: 'GET',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name getPipelineTasks
     * @description List the pipeline tasks, optionally filtering by project.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    getPipelineTasks: function (params) {
      var path = this.baseUrl + '/pipelines/tasks';

      var config = {
        method: 'GET',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name getProject
     * @description Get the specified instance.\n
     * @param {!number} projectId - HCE id of the &#x60;Project&#x60; to get.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    getProject: function (projectId, params) {
      var path = this.baseUrl + '/projects/{project_id}'
        .replace('{' + 'project_id' + '}', projectId);

      var config = {
        method: 'GET',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name getProjectMembers
     * @description Get the project members.
     * @param {!number} projectId - The instance id.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    getProjectMembers: function (projectId, params) {
      var path = this.baseUrl + '/projects/{project_id}/members'
        .replace('{' + 'project_id' + '}', projectId);

      var config = {
        method: 'GET',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name getProjects
     * @description List projects, optionally filtering.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    getProjects: function (params) {
      var path = this.baseUrl + '/projects';

      var config = {
        method: 'GET',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name removeMember
     * @description Remove a member (user) from a project.
     * @param {!number} projectId - The project id.
     * @param {object} data - the request body
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    removeMember: function (projectId, data, params) {
      var path = this.baseUrl + '/projects/{project_id}/members'
        .replace('{' + 'project_id' + '}', projectId);

      var config = {
        method: 'DELETE',
        url: path,
        params: params || {},
        data: data,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name removePipelineTask
     * @description Remove the specified pipeline task.
     * @param {!number} taskId - The PipelineTask id to remove.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    removePipelineTask: function (taskId, params) {
      var path = this.baseUrl + '/pipelines/tasks/{task_id}'
        .replace('{' + 'task_id' + '}', taskId);

      var config = {
        method: 'DELETE',
        url: path,
        params: params || {},
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name updateProject
     * @description Update the specified project.\n
     * @param {!number} projectId - The id of the &#x60;Project&#x60; instance.\n
     * @param {object} data - the request body
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    updateProject: function (projectId, data, params) {
      var path = this.baseUrl + '/projects/{project_id}'
        .replace('{' + 'project_id' + '}', projectId);

      var config = {
        method: 'PUT',
        url: path,
        params: params || {},
        data: data,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    }
  });
})();
