/* DO NOT EDIT: This code has been generated by swagger-codegen */
(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .run(registerApi);

  registerApi.$inject = [
    '$http',
    'app.api.apiManager'
  ];

  function registerApi($http, apiManager) {
    apiManager.register('cloud-foundry.api.HceUserApi', new HceUserApi($http));
  }

  /**
    * @constructor
    * @name HceUserApi
    * @description For more information on this API, please see:
    * https://github.com/hpcloud/hce-rest-service/blob/master/app/v2/swagger.yml
    * @param {object} $http - the Angular $http service
    * @property {object} $http - the Angular $http service
    * @property {string} baseUrl - the API base URL
    * @property {object} defaultHeaders - the default headers
    */
  function HceUserApi($http) {
    this.$http = $http;
    this.baseUrl = '/api/ce/v2';
    this.defaultHeaders = {
      Accept: 'application/json',
      'Content-Type': 'application/json'
    };
  }

  angular.extend(HceUserApi.prototype, {
    /**
     * @name createUser
     * @description Create a user.
     * @param {object} data - the request body
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    createUser: function (data, params) {
      var path = this.baseUrl + '/users';

      var config = {
        method: 'POST',
        url: path,
        params: params,
        data: data,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name deleteUser
     * @description Delete the specified user.
     * @param {!number} userId - User id.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    deleteUser: function (userId, params) {
      var path = this.baseUrl + '/users/{user_id}'
        .replace('{' + 'user_id' + '}', userId);

      var config = {
        method: 'DELETE',
        url: path,
        params: params,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name getUser
     * @description Get the specified user.
     * @param {!number} userId - User id.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    getUser: function (userId, params) {
      var path = this.baseUrl + '/users/{user_id}'
        .replace('{' + 'user_id' + '}', userId);

      var config = {
        method: 'GET',
        url: path,
        params: params,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name getUserByGithubId
     * @description Get the specified user.
     * @param {!number} githubId - Users github account id.
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    getUserByGithubId: function (githubId, params) {
      var path = this.baseUrl + '/users/github/{github_id}'
        .replace('{' + 'github_id' + '}', githubId);

      var config = {
        method: 'GET',
        url: path,
        params: params,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    },

    /**
     * @name updateUser
     * @description Update the specified user.
     * @param {!number} userId - User id.
     * @param {object} data - the request body
     * @param {object} params - the query parameters
     * @returns {promise} A resolved/rejected promise
     */
    updateUser: function (userId, data, params) {
      var path = this.baseUrl + '/users/{user_id}'
        .replace('{' + 'user_id' + '}', userId);

      var config = {
        method: 'PUT',
        url: path,
        params: params,
        data: data,
        headers: this.defaultHeaders
      };

      return this.$http(config);
    }
  });
})();
