/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.AppUsageEventsService', AppUsageEventsServiceFactory);

  function AppUsageEventsServiceFactory() {
    /* eslint-disable camelcase */
    function AppUsageEventsService($http) {

      this.ListAllAppUsageEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/app_usage_events";
        config.method = 'GET';
        $http(config);
      };

      this.PurgeAndReseedAppUsageEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/app_usage_events/destructively_purge_all_and_reseed_started_apps";
        config.method = 'POST';
        $http(config);
      };

      this.RetrieveAppUsageEvent = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/app_usage_events/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

    }

    return AppUsageEventsService;
    /* eslint-enable camelcase */
  }

})();
