/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.EnvironmentVariableGroupsService', EnvironmentVariableGroupsServiceFactory);

  function EnvironmentVariableGroupsServiceFactory() {
    /* eslint-disable camelcase */
    function EnvironmentVariableGroupsService($http) {

      this.GettingContentsOfRunningEnvironmentVariableGroup = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/config/environment_variable_groups/running";
        config.method = 'GET';
        $http(config);
      };

      this.GettingContentsOfStagingEnvironmentVariableGroup = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/config/environment_variable_groups/staging";
        config.method = 'GET';
        $http(config);
      };

      this.UpdateContentsOfRunningEnvironmentVariableGroup = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/config/environment_variable_groups/running";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

      this.UpdateContentsOfStagingEnvironmentVariableGroup = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/config/environment_variable_groups/staging";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

    }

    return EnvironmentVariableGroupsService;
    /* eslint-enable camelcase */
  }

})();
