/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.EventsService', EventsServiceFactory);

  function EventsServiceFactory() {
    /* eslint-disable camelcase */
    function EventsService($http) {

      this.ListAllEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListAppCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListAppDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListAppExitedEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListAppSshAuthorizedEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListAppSshUnauthorizedEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListAppStartEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListAppStopEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListAppUpdateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListEventsAssociatedWithAppSinceJanuary12014 = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceBindingCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceBindingDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceBrokerCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceBrokerDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceBrokerUpdateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceDashboardClientCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceDashboardClientDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceInstanceCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceInstanceDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceInstanceUpdateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceKeyCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceKeyDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServicePlanCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServicePlanDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServicePlanUpdateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServicePlanVisibilityCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServicePlanVisibilityDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServicePlanVisibilityUpdateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListServiceUpdateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListSpaceCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListSpaceDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListSpaceUpdateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListUserProvidedServiceInstanceCreateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListUserProvidedServiceInstanceDeleteEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.ListUserProvidedServiceInstanceUpdateEvents = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveEvent = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/events/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

    }

    return EventsService;
    /* eslint-enable camelcase */
  }

})();
