/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.InfoService', InfoServiceFactory);

  function InfoServiceFactory() {
    /* eslint-disable camelcase */
    function InfoService($http) {

      this.GetInfo = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/info";
        config.method = 'GET';
        $http(config);
      };

    }

    return InfoService;
    /* eslint-enable camelcase */
  }

})();
