/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.JobsService', JobsServiceFactory);

  function JobsServiceFactory() {
    /* eslint-disable camelcase */
    function JobsService($http) {

      this.RetrieveJobThatIsQueued = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/jobs/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveJobThatWasSuccessful = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/jobs/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveJobWithKnownFailure = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/jobs/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveJobWithUnknownFailure = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/jobs/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

    }

    return JobsService;
    /* eslint-enable camelcase */
  }

})();
