/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.OrganizationQuotaDefinitionsService', OrganizationQuotaDefinitionsServiceFactory);

  function OrganizationQuotaDefinitionsServiceFactory() {
    /* eslint-disable camelcase */
    function OrganizationQuotaDefinitionsService($http) {

      this.CreateOrganizationQuotaDefinition = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/quota_definitions";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteOrganizationQuotaDefinition = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/quota_definitions/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllOrganizationQuotaDefinitions = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/quota_definitions";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveOrganizationQuotaDefinition = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/quota_definitions/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.UpdateOrganizationQuotaDefinition = function (guid, value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/quota_definitions/" + guid + "";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

    }

    return OrganizationQuotaDefinitionsService;
    /* eslint-enable camelcase */
  }

})();
