/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.ResourceMatchService', ResourceMatchServiceFactory);

  function ResourceMatchServiceFactory() {
    /* eslint-disable camelcase */
    function ResourceMatchService($http) {

      this.ListAllMatchingResources = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/resource_match";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

    }

    return ResourceMatchService;
    /* eslint-enable camelcase */
  }

})();
