/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.SecurityGroupRunningDefaultsService', SecurityGroupRunningDefaultsServiceFactory);

  function SecurityGroupRunningDefaultsServiceFactory() {
    /* eslint-disable camelcase */
    function SecurityGroupRunningDefaultsService($http) {

      this.RemovingSecurityGroupAsDefaultForRunningApps = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/config/running_security_groups/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ReturnSecurityGroupsUsedForRunningApps = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/config/running_security_groups";
        config.method = 'GET';
        $http(config);
      };

      this.SetSecurityGroupAsDefaultForRunningApps = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/config/running_security_groups/" + guid + "";
        config.method = 'PUT';
        $http(config);
      };

    }

    return SecurityGroupRunningDefaultsService;
    /* eslint-enable camelcase */
  }

})();
