/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.SecurityGroupsService', SecurityGroupsServiceFactory);

  function SecurityGroupsServiceFactory() {
    /* eslint-disable camelcase */
    function SecurityGroupsService($http) {

      this.AssociateSpaceWithSecurityGroup = function (guid, space_guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/security_groups/" + guid + "/spaces/" + space_guid + "";
        config.method = 'PUT';
        $http(config);
      };

      this.CreateSecurityGroup = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/security_groups";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteSecurityGroup = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/security_groups/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllSecurityGroups = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/security_groups";
        config.method = 'GET';
        $http(config);
      };

      this.ListAllSpacesForSecurityGroup = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/security_groups/" + guid + "/spaces";
        config.method = 'GET';
        $http(config);
      };

      this.RemoveSpaceFromSecurityGroup = function (guid, space_guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/security_groups/" + guid + "/spaces/" + space_guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.RetrieveSecurityGroup = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/security_groups/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.UpdateSecurityGroup = function (guid, value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/security_groups/" + guid + "";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

    }

    return SecurityGroupsService;
    /* eslint-enable camelcase */
  }

})();
