/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.ServicePlansService', ServicePlansServiceFactory);

  function ServicePlansServiceFactory() {
    /* eslint-disable camelcase */
    function ServicePlansService($http) {

      this.CreateServicePlanDeprecated = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plans";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteServicePlans = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plans/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllServiceInstancesForServicePlan = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plans/" + guid + "/service_instances";
        config.method = 'GET';
        $http(config);
      };

      this.ListAllServicePlans = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plans";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveServicePlan = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plans/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.UpdateServicePlanDeprecated = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plans";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

    }

    return ServicePlansService;
    /* eslint-enable camelcase */
  }

})();
