/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.ServicesService', ServicesServiceFactory);

  function ServicesServiceFactory() {
    /* eslint-disable camelcase */
    function ServicesService($http) {

      this.CreateServiceDeprecated = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/services";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteService = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/services/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllServicePlansForService = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/services/" + guid + "/service_plans";
        config.method = 'GET';
        $http(config);
      };

      this.ListAllServices = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/services";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveService = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/services/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.UpdateServiceDeprecated = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/services";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

    }

    return ServicesService;
    /* eslint-enable camelcase */
  }

})();
