/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.ServiceBindingsService', ServiceBindingsServiceFactory);

  function ServiceBindingsServiceFactory() {
    /* eslint-disable camelcase */
    function ServiceBindingsService($http) {

      this.CreateServiceBinding = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_bindings";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteServiceBinding = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_bindings/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllServiceBindings = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_bindings";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveServiceBinding = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_bindings/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

    }

    return ServiceBindingsService;
    /* eslint-enable camelcase */
  }

})();
