/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.ServiceKeysService', ServiceKeysServiceFactory);

  function ServiceKeysServiceFactory() {
    /* eslint-disable camelcase */
    function ServiceKeysService($http) {

      this.CreateServiceKey = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_keys";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteServiceKey = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_keys/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllServiceKeys = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_keys";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveServiceKey = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_keys/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

    }

    return ServiceKeysService;
    /* eslint-enable camelcase */
  }

})();
