/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.ServiceAuthTokensDeprecatedService', ServiceAuthTokensDeprecatedServiceFactory);

  function ServiceAuthTokensDeprecatedServiceFactory() {
    /* eslint-disable camelcase */
    function ServiceAuthTokensDeprecatedService($http) {

      this.DeleteServiceAuthTokenDeprecated = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_auth_tokens/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.FilterResultSetByLabelDeprecated = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_auth_tokens";
        config.method = 'GET';
        $http(config);
      };

      this.FilterResultSetByProviderDeprecated = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_auth_tokens";
        config.method = 'GET';
        $http(config);
      };

      this.ListAllServiceAuthTokensDeprecated = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_auth_tokens";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveServiceAuthTokenDeprecated = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_auth_tokens/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

    }

    return ServiceAuthTokensDeprecatedService;
    /* eslint-enable camelcase */
  }

})();
