/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.ServiceBrokersService', ServiceBrokersServiceFactory);

  function ServiceBrokersServiceFactory() {
    /* eslint-disable camelcase */
    function ServiceBrokersService($http) {

      this.CreateServiceBroker = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_brokers";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteServiceBroker = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_brokers/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllServiceBrokers = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_brokers";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveServiceBroker = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_brokers/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.UpdateServiceBroker = function (guid, value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_brokers/" + guid + "";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

    }

    return ServiceBrokersService;
    /* eslint-enable camelcase */
  }

})();
