/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.ServicePlanVisibilitiesService', ServicePlanVisibilitiesServiceFactory);

  function ServicePlanVisibilitiesServiceFactory() {
    /* eslint-disable camelcase */
    function ServicePlanVisibilitiesService($http) {

      this.CreateServicePlanVisibility = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plan_visibilities";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteServicePlanVisibilities = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plan_visibilities/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllServicePlanVisibilities = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plan_visibilities";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveServicePlanVisibility = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plan_visibilities/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.UpdateServicePlanVisibility = function (guid, value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/service_plan_visibilities/" + guid + "";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

    }

    return ServicePlanVisibilitiesService;
    /* eslint-enable camelcase */
  }

})();
