/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.SharedDomainsService', SharedDomainsServiceFactory);

  function SharedDomainsServiceFactory() {
    /* eslint-disable camelcase */
    function SharedDomainsService($http) {

      this.CreateSharedDomain = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/shared_domains";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteSharedDomain = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/shared_domains/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.FilterSharedDomainsByName = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/shared_domains";
        config.method = 'GET';
        $http(config);
      };

      this.ListAllSharedDomains = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/shared_domains";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveSharedDomain = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/shared_domains/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

    }

    return SharedDomainsService;
    /* eslint-enable camelcase */
  }

})();
