/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.SpaceQuotaDefinitionsService', SpaceQuotaDefinitionsServiceFactory);

  function SpaceQuotaDefinitionsServiceFactory() {
    /* eslint-disable camelcase */
    function SpaceQuotaDefinitionsService($http) {

      this.AssociateSpaceWithSpaceQuotaDefinition = function (guid, space_guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/space_quota_definitions/" + guid + "/spaces/" + space_guid + "";
        config.method = 'PUT';
        $http(config);
      };

      this.CreateSpaceQuotaDefinition = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/space_quota_definitions";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteSpaceQuotaDefinition = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/space_quota_definitions/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllSpaceQuotaDefinitions = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/space_quota_definitions";
        config.method = 'GET';
        $http(config);
      };

      this.ListAllSpacesForSpaceQuotaDefinition = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/space_quota_definitions/" + guid + "/spaces";
        config.method = 'GET';
        $http(config);
      };

      this.RemoveSpaceFromSpaceQuotaDefinition = function (guid, space_guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/space_quota_definitions/" + guid + "/spaces/" + space_guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.RetrieveSpaceQuotaDefinition = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/space_quota_definitions/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.UpdateSpaceQuotaDefinition = function (guid, value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/space_quota_definitions/" + guid + "";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

    }

    return SpaceQuotaDefinitionsService;
    /* eslint-enable camelcase */
  }

})();
