/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.StacksService', StacksServiceFactory);

  function StacksServiceFactory() {
    /* eslint-disable camelcase */
    function StacksService($http) {

      this.CreateStack = function (value, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/stacks";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeleteStack = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/stacks/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.ListAllStacks = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v2/stacks";
        config.method = 'GET';
        $http(config);
      };

      this.RetrieveStack = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v2/stacks/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

    }

    return StacksService;
    /* eslint-enable camelcase */
  }

})();
