// AUTO-GENERATED - DO NOT EDIT
// Generated by extension-generator.js

import { NgModule } from '@angular/core';
import { CfAutoscalerPackageModule, CfAutoscalerRoutingModule } from '@stratosui/cf-autoscaler';
import { CloudFoundryPackageModule, CloudFoundryRoutingModule } from '@stratosui/cloud-foundry';
import { GitPackageModule } from '@stratosui/git';
import { KubePackageModule, KubePackageModuleRoutingModule } from '@stratosui/kubernetes';

@NgModule({
  imports: [
    CfAutoscalerPackageModule,
    CloudFoundryPackageModule,
    GitPackageModule,
    KubePackageModule
  ]
})
export class CustomImportModule {}


@NgModule({
  imports: [
    CfAutoscalerRoutingModule,
    CloudFoundryRoutingModule,
    KubePackageModuleRoutingModule
  ]
})
export class CustomRoutingImportModule {}
