FROM bosh/cli2

RUN apt-get update
RUN apt-get install -y git curl wget
RUN curl https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz -o /go1.8.3.tar.gz
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - && \
    sudo apt-get install -y nodejs
RUN tar -C /usr/local -xzf /go1.8.3.tar.gz
RUN mkdir -p /root/go/bin
ENV GOPATH /root/go
ENV PATH $PATH:/usr/local/go/bin:/root/go/bin
