FROM alpine:3.6
RUN apk add --update --no-cache ca-certificates git curl
ENV VERSION v2.6.1
ENV FILENAME helm-${VERSION}-linux-amd64.tar.gz
RUN curl -L http://storage.googleapis.com/kubernetes-helm/${FILENAME} | tar xzv && \
    mv /linux-amd64/helm /bin/helm
