export const ApiActionTypes = {
  API_REQUEST: 'API_REQUEST',
  API_REQUEST_START: 'API_REQUEST_START',
  API_REQUEST_SUCCESS: 'API_REQUEST_SUCCESS',
  API_REQUEST_FAILED: 'API_REQUEST_FAILED',
};

export const NonApiActionTypes = {
  START: 'NONE_API_REQUEST_START',
  SUCCESS: 'NONE_API_REQUEST_SUCCESS',
  FAILED: 'NONE_API_REQUEST_FAILED',
};
