FROM splatform/stratos-concourse

# These args need to be consumed, otherwise build fails
ARG USER_ID
ARG GROUP_ID
ARG USER_NAME
ENV LANG en_US.UTF-8
ENV DBUS_SESSION_BUS_ADDRESS /dev/null
WORKDIR /usr/src/app
CMD bash test/e2e/provision.sh && npm run headless-e2e -- --params.host=nginx --params.port=
