FROM splatform/stratos-bk-base:opensuse as prod-build
USER root
RUN zypper in -y wget tar unzip nano vim curl

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

# Install Helm

RUN curl -LO https://git.io/get_helm.sh && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh

ADD ./kubeconsole.bashrc /root/.bashrc
WORKDIR /root

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
