FROM splatform/stratos-preflight-base:opensuse

RUN mkdir -p /srv
WORKDIR /srv
COPY outputs/* /srv/
COPY /deploy/db/scripts/run-preflight-job.sh /run-preflight-job.sh
COPY /deploy/tools/generate_cert.sh /generate_cert.sh
RUN chmod +x portal-proxy
EXPOSE 443
CMD ["bash", "-c", "/run-preflight-job.sh; /srv/portal-proxy"]
