FROM splatform/stratos-bk-build-base:opensuse

RUN mkdir -p /go/src/github.com/SUSE/stratos-ui
COPY package.json /
RUN cd / && npm install
WORKDIR /go/src/github.com/SUSE/stratos-ui
ENV GLIDE_HOME /.glide
COPY glide-cache /.glide
COPY compile.sh /
CMD ["/compile.sh"]
