FROM splatform/stratos-ui-build-base:opensuse

ARG USER_ID
ARG GROUP_ID
ARG USER_NAME

# Run this as a normal with the specified ID
RUN user_exists=$(getent passwd ${USER_ID} | cut -d: -f1); \
  group_exists=$(getent group ${GROUP_ID} | cut -d: -f1); \
  if [ -z "${group_exists}" ]; then \
    groupadd -r -g ${GROUP_ID} ${USER_NAME}; \
    else \
      echo "Group with gid ${GROUP_ID} already exists."; \
    fi ;\
    if [ -z "${user_exists}" ]; then \
      useradd -m -r -g ${GROUP_ID} -u ${USER_ID} ${USER_NAME}; \
      else \
        echo "User with uid ${USER_ID} already exists."; \
      fi

COPY . /usr/src/app

# Chnage ownership so that our user can create new files
RUN chown ${USER_ID}:${GROUP_ID} /usr/src/app

RUN chown ${USER_ID}:${GROUP_ID} /usr/src/app/.angular-cli.json
RUN sed -i.bak "s@\"dist\"@\"/usr/dist/dist\"@g" /usr/src/app/.angular-cli.json

USER ${USER_ID}

WORKDIR /usr/src/app

CMD bash deploy/provision.sh
