FROM alpine:latest

RUN apk update && \
    apk add ca-certificates openssl git &&\
    mkdir -p /srv

WORKDIR /srv
COPY outputs/* /srv/
COPY /deploy/db/scripts/run-preflight-job.sh /run-preflight-job.sh
COPY dev-certs dev-certs
RUN chmod +x portal-proxy
EXPOSE 443
CMD ["sh", "-c", "/run-preflight-job.sh; /srv/portal-proxy"]
