FROM nginx
RUN mkdir -p /usr/share/doc/suse
COPY ./LICENSE.txt /usr/share/doc/suse/LICENSE.txt
COPY ./conf/nginx.k8s.conf /etc/nginx/nginx.conf
COPY ./dist/ /usr/share/nginx/html
EXPOSE 80 443
CMD [ "nginx", "-g", "daemon off;" ]
