FROM golang:1.6

RUN go get bitbucket.org/liamstask/goose/cmd/goose

WORKDIR /src

COPY db/dbconf.yml db/dbconf.yml
COPY db/migrations db/migrations
COPY db/scripts/development.sh .
COPY db/scripts/wait-for-it.sh .
RUN chmod +x wait-for-it.sh
RUN chmod +x development.sh

CMD bash /src/wait-for-it.sh postgres:5432 && bash /src/development.sh
