FROM golang:1.6

ENV DB_HOST="hsc-db-int" CFGDB_PORT=5432 \
  POSTGRES_DB="postgres" POSTGRES_USER="stolon" POSTGRES_PASSWORD="stolon" \
  PGSQL_DATABASE="stratos-db" PGSQL_USER="stratos" PGSQL_PASSWORD="stratos" \

RUN apt-get update && apt-get install -y gcc postgresql

RUN go get 'bitbucket.org/liamstask/goose/cmd/goose'
RUN chmod +x /go/bin/goose

COPY /dbconf.yml /
COPY /migrations /
COPY /run-preflight-job.sh /

CMD ["/run-preflight-job.sh"]
