FROM {{BASE_IMAGE}}

RUN yum update -y && \
    yum install -y git gcc wget gzip xz unzip
    
RUN wget https://storage.googleapis.com/golang/go1.20.7.linux-{{GO_ARCH}}.tar.gz && \
    tar -xzf go1.20.7.linux-{{GO_ARCH}}.tar.gz -C /usr/local/ && \
    rm go1.20.7.linux-{{GO_ARCH}}.tar.gz && \
    mkdir -p /home/stratos/go/bin && \
    mkdir -p /home/stratos/go/src
    
ENV PATH $PATH:/usr/local/go/bin:/home/stratos/go/bin
ENV GOPATH /home/stratos/go

WORKDIR /home/stratos/go
