FROM {{BASE_IMAGE}}

{{#IS_SLE}}
RUN zypper addrepo  -G -c '{{SMT_INTERNAL}}' smt_internal
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_UPDATE}}' smt_internal_update
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_SDK}}' smt_internal_sdk
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_SERVER}}' smt_internal_server
RUN zypper ref
{{/IS_SLE}}

RUN zypper -n ref && \
zypper -n up && \
zypper in -y wget tar git
RUN cd / && wget https://nodejs.org/dist/v8.11.2/node-v8.11.2-linux-x64.tar.xz && \
    tar -xf node-v8.11.2-linux-x64.tar.xz
ENV USER=stratos
ENV PATH=$PATH:/node-v8.11.2-linux-x64/bin
RUN useradd -ms /bin/bash stratos && \
    mkdir -p /home/stratos && \
    chown -R stratos /home/stratos && \
    chgrp -R users /home/stratos && \
    mkdir -p /usr/dist && \
    chown stratos /usr/dist && \
    chgrp users /usr/dist

{{#IS_SLE}}
RUN zypper rr  smt_internal
RUN zypper rr  smt_internal_update
RUN zypper rr  smt_internal_sdk
RUN zypper rr  smt_internal_server
{{/IS_SLE}}

USER stratos
WORKDIR /home/stratos