FROM {{BASE_IMAGE}}

RUN zypper -n ref && \
zypper -n up && \
zypper in -y wget tar git
RUN wget https://nodejs.org/dist/v8.6.0/node-v8.6.0-linux-x64.tar.xz && \
tar -xf node-v8.6.0-linux-x64.tar.xz
ENV PATH $PATH:/node-v8.6.0-linux-x64/bin