FROM {{BASE_IMAGE}}

RUN zypper -n ref && \
zypper -n up && \
zypper in -y which tar git gcc curl wget
RUN wget https://storage.googleapis.com/golang/go1.9.7.linux-amd64.tar.gz && \
    tar -xzf go1.9.7.linux-amd64.tar.gz -C /usr/local/ && \
    mkdir -p /home/stratos/go/bin && \
    mkdir -p /home/stratos/go/src
    
ENV PATH $PATH:/usr/local/go/bin:/home/stratos/go/bin
ENV GOPATH /home/stratos/go

# Install both glide and dep for now, so that this base image can use either

# Install glide for backend go dependency management (legacy)
RUN curl https://glide.sh/get | sh

# Install dep for backend go dependency management
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

WORKDIR /home/stratos/go
