FROM {{BASE_IMAGE}}

RUN zypper -n ref && \
zypper -n up && \
zypper in -y wget tar git
RUN cd / && wget https://nodejs.org/dist/v6.11.4/node-v6.11.4-linux-x64.tar.xz && \
tar -xf node-v6.11.4-linux-x64.tar.xz
ENV PATH $PATH:/node-v6.11.4-linux-x64/bin
