FROM {{BASE_IMAGE}}

{{#IS_SLE}}
RUN rm -f /usr/lib/zypp/plugins/services/container-suseconnect-zypp
RUN zypper addrepo  -G -c '{{SMT_INTERNAL}}' smt_internal
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_UPDATE}}' smt_internal_update
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_SDK}}' smt_internal_sdk
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_SERVER}}' smt_internal_server
RUN zypper ref
{{/IS_SLE}}
RUN zypper in -y ca-certificates && \
    zypper in -y curl && \
    zypper in -y openssh && \
    zypper in -y jq && \
    zypper in -y bind-utils && \
    zypper in -y hostname && \
    mkdir -p /srv && \
    mkdir -p /root/.npm-global

{{#IS_SLE}}
RUN zypper rr smt_internal
RUN zypper rr smt_internal_update
RUN zypper rr smt_internal_sdk
RUN zypper rr smt_internal_server
{{/IS_SLE}}
WORKDIR /srv
