FROM {{BASE_IMAGE}}

RUN zypper -n ref && \
zypper -n up && \
zypper in -y wget which tar git gcc
RUN wget https://storage.googleapis.com/golang/go1.8.4.linux-amd64.tar.gz && \
    tar -xzf go1.8.4.linux-amd64.tar.gz -C /usr/local/ && \
    mkdir -p /go/bin && \
    mkdir -p /go/src
ENV PATH $PATH:/usr/local/go/bin:/go/bin
ENV GOPATH /go
RUN wget https://glide.sh/get && \
    chmod +x get && \
    ./get
WORKDIR /go