FROM {{BASE_IMAGE}}

{{#IS_SLE}}
RUN rm -f /usr/lib/zypp/plugins/services/container-suseconnect-zypp
RUN zypper addrepo  -G -c '{{SMT_INTERNAL}}' smt_internal
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_UPDATE}}' smt_internal_update
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_SDK}}' smt_internal_sdk
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_SERVER}}' smt_internal_server
RUN zypper ref
{{/IS_SLE}}
RUN zypper in -y ca-certificates && \
    # Can remove this when we remove the postflight job
    zypper in -y mariadb-client curl && \
    mkdir -p /srv && \
    mkdir -p /root/.npm-global
# Install latest git from devel/tools/scm repository
{{^IS_SLE}}
RUN zypper ar http://download.opensuse.org/repositories/devel:/tools:/scm/openSUSE_Leap_15.1/devel:tools:scm.repo && \
    zypper --no-gpg-checks in -y git && \
    zypper rr devel_tools_scm && \
    zypper clean -a && \
    rm -f /var/log/zypper.log /var/log/zypp/history

{{/IS_SLE}}
{{#IS_SLE}}
RUN zypper ar http://download.opensuse.org/repositories/devel:/tools:/scm/SLE_15/devel:tools:scm.repo && \
    zypper --no-gpg-checks in -y git && \
    zypper rr devel_tools_scm && \
    zypper clean -a && \
    rm -f /var/log/zypper.log /var/log/zypp/history

{{/IS_SLE}}

{{#IS_SLE}}
RUN zypper rr smt_internal
RUN zypper rr smt_internal_update
RUN zypper rr smt_internal_sdk
RUN zypper rr smt_internal_server
{{/IS_SLE}}
WORKDIR /srv
