FROM {{BASE_IMAGE}}

RUN zypper -n ref && \
zypper -n up && \
zypper in -y wget tar git
RUN cd / && wget https://nodejs.org/dist/v8.11.2/node-v8.11.2-linux-x64.tar.xz && \
    tar -xf node-v8.11.2-linux-x64.tar.xz
ENV USER=stratos
ENV PATH=$PATH:/node-v8.11.2-linux-x64/bin
RUN useradd -ms /bin/bash stratos && \
    mkdir -p /home/stratos && \
    chown -R stratos /home/stratos && \
    chgrp -R users /home/stratos && \
    mkdir -p /usr/dist && \
    chown stratos /usr/dist && \
    chgrp users /usr/dist

USER stratos
WORKDIR /home/stratos