FROM {{BASE_IMAGE}}

{{#IS_SLE}}
RUN rm -f /usr/lib/zypp/plugins/services/container-suseconnect-zypp
RUN zypper addrepo  -G -c '{{SMT_INTERNAL}}' smt_internal
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_UPDATE}}' smt_internal_update
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_SDK}}' smt_internal_sdk
RUN zypper addrepo -t rpm-md -G -c '{{SMT_INTERNAL_SERVER}}' smt_internal_server
RUN zypper ref
{{/IS_SLE}}

RUN zypper -n ref && \
    zypper -n up && \
    zypper in -y which tar curl wget gzip && \
    zypper clean -a && \
    rm -f /var/log/zypper.log /var/log/zypp/history

WORKDIR /
USER root

ADD install-ruby.sh /install-ruby.sh
RUN /install-ruby.sh

{{#IS_SLE}}
RUN zypper rr smt_internal
RUN zypper rr smt_internal_update
RUN zypper rr smt_internal_sdk
RUN zypper rr smt_internal_server
{{/IS_SLE}}
