FROM {{BASE_IMAGE}}

{{#IS_SLE}}
RUN zypper addrepo  -G -c '{{SMT_INTERNAL}}' smt_internal
RUN zypper ref
{{/IS_SLE}}

# Default password for root of mariadb
ENV MYSQL_ROOT_PASSWORD mysecretpassword

# Add repo for the latest mariadb
RUN zypper in -y mariadb net-tools mariadb-tools timezone wget && \
    zypper clean -a && \
    rm -f /var/log/zypper.log /var/log/zypp/history

ARG GOSU_VERSION=1.11
RUN wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
    && chmod +x /usr/local/bin/gosu

# Config for mariadb
RUN rm -rf /var/lib/mysql \
  && mkdir -p /var/lib/mysql \
  && mkdir -p /var/log/mysql \
  && touch /var/log/mysql/mysqld.log \
  && chown -R mysql:mysql /var/log/mysql

{{#IS_SLE}}
RUN zypper rr  smt_internal
{{/IS_SLE}}

VOLUME ["/var/lib/mysql"]