/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .run(registerApi);

  registerApi.$inject = [
    '$http',
    'app.api.apiManager'
  ];

  function registerApi($http, apiManager) {
    apiManager.register('cloud-foundry.api.DropletsExperimental', new DropletsExperimentalApi($http));
  }

  function DropletsExperimentalApi($http) {
    this.$http = $http;
  }

  /* eslint-disable camelcase */
  angular.extend(DropletsExperimentalApi.prototype, {

   /*
    * Delete a Droplet
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/195/droplets__experimental_/delete_a_droplet.html
    */
    DeleteDroplet: function (guid, params) {
      var config = {};
      config.params = params;
      config.url = "/api/cf/v3/droplets/" + guid + "";
      config.method = 'DELETE';
      return this.$http(config);
    },

   /*
    * Filters Droplets by states, app_guids
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/195/droplets__experimental_/filters_droplets_by_states,_app_guids.html
    */
    FiltersDropletsByStatesAppGuids: function (params) {
      var config = {};
      config.params = params;
      config.url = "/api/cf/v3/droplets";
      config.method = 'GET';
      return this.$http(config);
    },

   /*
    * Get a Droplet
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/195/droplets__experimental_/get_a_droplet.html
    */
    GetDroplet: function (guid, params) {
      var config = {};
      config.params = params;
      config.url = "/api/cf/v3/droplets/" + guid + "";
      config.method = 'GET';
      return this.$http(config);
    },

   /*
    * List all Droplets
    * For detailed information, see online documentation at: http://apidocs.cloudfoundry.org/195/droplets__experimental_/list_all_droplets.html
    */
    ListAllDroplets: function (params) {
      var config = {};
      config.params = params;
      config.url = "/api/cf/v3/droplets";
      config.method = 'GET';
      return this.$http(config);
    }

  });
  /* eslint-enable camelcase */

})();
