/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.PackagesExperimentalService', PackagesExperimentalServiceFactory);

  function PackagesExperimentalServiceFactory() {
    /* eslint-disable camelcase */
    function PackagesExperimentalService($http) {

      this.CopyPackage = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v3/apps/" + guid + "/packages";
        config.method = 'POST';
        $http(config);
      };

      this.CreatePackage = function (guid, value, params) {
        var config = {};
        config.params = params;
        config.url = "/v3/apps/" + guid + "/packages";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

      this.DeletePackage = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v3/packages/" + guid + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.GetPackage = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v3/packages/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.ListAllPackages = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v3/packages";
        config.method = 'GET';
        $http(config);
      };

      this.StagePackage = function (guid, value, params) {
        var config = {};
        config.params = params;
        config.url = "/v3/packages/" + guid + "/droplets";
        config.method = 'POST';
        config.data = value;
        $http(config);
      };

    }

    return PackagesExperimentalService;
    /* eslint-enable camelcase */
  }

})();
