/* DO NOT EDIT: This code has been generated by the cf-dotnet-sdk-builder */

(function () {
  'use strict';

  angular
    .module('cloud-foundry.api')
    .factory('cloud-foundry.api.ProcessesExperimentalService', ProcessesExperimentalServiceFactory);

  function ProcessesExperimentalServiceFactory() {
    /* eslint-disable camelcase */
    function ProcessesExperimentalService($http) {

      this.GetProcess = function (guid, params) {
        var config = {};
        config.params = params;
        config.url = "/v3/processes/" + guid + "";
        config.method = 'GET';
        $http(config);
      };

      this.ListAllProcesses = function (params) {
        var config = {};
        config.params = params;
        config.url = "/v3/processes";
        config.method = 'GET';
        $http(config);
      };

      this.ScalingProcess = function (guid, value, params) {
        var config = {};
        config.params = params;
        config.url = "/v3/processes/" + guid + "/scale";
        config.method = 'PUT';
        config.data = value;
        $http(config);
      };

      this.TerminatingProcessInstance = function (guid, index, params) {
        var config = {};
        config.params = params;
        config.url = "/v3/processes/" + guid + "/instances/" + index + "";
        config.method = 'DELETE';
        $http(config);
      };

      this.UpdateProcess = function (guid, value, params) {
        var config = {};
        config.params = params;
        config.url = "/v3/processes/" + guid + "";
        config.method = 'PATCH';
        config.data = value;
        $http(config);
      };

    }

    return ProcessesExperimentalService;
    /* eslint-enable camelcase */
  }

})();
