FROM node:6.9

COPY package.json /
RUN npm install
RUN echo 'Europe/London' > /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata
# Due to a conflict in Gulp 3, we need to run this again
RUN npm install
