import { test, expect } from '../../fixtures/test-base';

/**
 * About Page E2E Tests
 *
 * Verifies version information is displayed correctly on the About page.
 * Frontend build info comes from BUILD_INFO (generated by `make fe-version`).
 * Backend version info comes from the session API (/api/v1/auth/session/verify).
 *
 * Use this test to confirm which build is deployed — frontend and backend
 * versions should match the intentional build numbers.
 */
test.describe('About Page', () => {

  test('should display the about page', async ({ connectedEndpointsAdminPage }) => {
    const page = connectedEndpointsAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    await expect(page.locator('.page-header').first()).toBeVisible();
  });

  test('should display frontend version information', async ({ connectedEndpointsAdminPage }) => {
    const page = connectedEndpointsAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    // Frontend section heading
    await expect(page.locator('text=Frontend')).toBeVisible({ timeout: 10000 });

    // Version field should be visible and match semver
    const versionDt = page.locator('dt', { hasText: 'Version' }).first();
    await expect(versionDt).toBeVisible();
    const versionDd = versionDt.locator('..').locator('dd');
    const versionText = await versionDd.textContent();
    expect(versionText?.trim()).toMatch(/v?\d+\.\d+\.\d+/);
  });

  test('should display frontend commit and branch', async ({ connectedEndpointsAdminPage }) => {
    const page = connectedEndpointsAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    // Commit should be a short SHA
    const commitDt = page.locator('dt', { hasText: 'Commit' }).first();
    await expect(commitDt).toBeVisible({ timeout: 10000 });
    const commitDd = commitDt.locator('..').locator('dd');
    const commitText = await commitDd.textContent();
    expect(commitText?.trim().length).toBeGreaterThan(0);

    // Branch should be visible
    const branchDt = page.locator('dt', { hasText: 'Branch' }).first();
    await expect(branchDt).toBeVisible();
    const branchDd = branchDt.locator('..').locator('dd');
    const branchText = await branchDd.textContent();
    expect(branchText?.trim().length).toBeGreaterThan(0);
  });

  test('should display backend version information', async ({ connectedEndpointsAdminPage }) => {
    const page = connectedEndpointsAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    // Backend section heading
    await expect(page.locator('text=Backend')).toBeVisible({ timeout: 10000 });

    // Both frontend and backend have Version fields
    const versionFields = page.locator('dt', { hasText: 'Version' });
    await expect(versionFields).toHaveCount(2);
  });

  test('should display database version', async ({ connectedEndpointsAdminPage }) => {
    const page = connectedEndpointsAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    const dbDt = page.locator('dt', { hasText: 'Database' });
    await expect(dbDt).toBeVisible({ timeout: 10000 });
    const dbDd = dbDt.locator('..').locator('dd');
    const dbText = await dbDd.textContent();
    expect(dbText?.trim().length).toBeGreaterThan(0);
  });

  test('should show admin diagnostics button for admin users', async ({ connectedEndpointsAdminPage }) => {
    const page = connectedEndpointsAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    await expect(page.locator('text=You have administrative privileges')).toBeVisible({ timeout: 10000 });
    await expect(page.locator('button:has-text("View Diagnostics")')).toBeVisible();
  });

  test('should display Angular version in frontend section', async ({ connectedEndpointsAdminPage }) => {
    const page = connectedEndpointsAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    const angularDt = page.locator('dt', { hasText: 'Angular' });
    await expect(angularDt).toBeVisible({ timeout: 10000 });
    const angularDd = angularDt.locator('..').locator('dd');
    const text = await angularDd.textContent();
    expect(text?.trim()).toMatch(/^\d+\.\d+\.\d+/);
  });

  test('frontend and backend versions should both be present', async ({ connectedEndpointsAdminPage }) => {
    const page = connectedEndpointsAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    // Both frontend and backend Version fields
    const versionFields = page.locator('dt', { hasText: 'Version' });
    const count = await versionFields.count();
    expect(count).toBe(2);

    // Both should have non-empty values
    for (let i = 0; i < count; i++) {
      const dd = versionFields.nth(i).locator('..').locator('dd');
      const text = await dd.textContent();
      expect(text?.trim().length).toBeGreaterThan(0);
    }
  });

});
