import { test, expect } from '../../fixtures/test-base';

/**
 * About Page E2E Tests
 *
 * Verifies version information is displayed correctly on the About page.
 * Frontend build info comes from BUILD_INFO (generated by `make fe-version`).
 * Backend version info comes from the session API (/api/v1/auth/session/verify).
 *
 * Use this test to confirm which build is deployed — frontend and backend
 * versions should match the intentional build numbers.
 */
test.describe('About Page', () => {

  test('should display the about page', async ({ loggedInAdminPage }) => {
    const page = loggedInAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    await expect(page.locator('app-page-header')).toBeVisible();
  });

  test('should display frontend version information', async ({ loggedInAdminPage }) => {
    const page = loggedInAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    // Frontend section heading
    await expect(page.locator('text=Frontend')).toBeVisible({ timeout: 10000 });

    // Version field should be visible and non-empty
    const versionItem = page.locator('app-metadata-item').filter({ hasText: /^Version/ }).first();
    await expect(versionItem).toBeVisible();
    const versionText = await versionItem.textContent();
    expect(versionText).toMatch(/v?\d+\.\d+\.\d+/);
  });

  test('should display frontend commit and branch', async ({ loggedInAdminPage }) => {
    const page = loggedInAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    // Commit should be a short SHA
    const commitItem = page.locator('app-metadata-item').filter({ hasText: /^Commit/ }).first();
    await expect(commitItem).toBeVisible({ timeout: 10000 });
    const commitText = await commitItem.textContent();
    expect(commitText?.replace('Commit', '').trim().length).toBeGreaterThan(0);

    // Branch should be visible
    const branchItem = page.locator('app-metadata-item').filter({ hasText: /^Branch/ });
    await expect(branchItem).toBeVisible();
    const branchText = await branchItem.textContent();
    expect(branchText?.replace('Branch', '').trim().length).toBeGreaterThan(0);
  });

  test('should display backend version information', async ({ loggedInAdminPage }) => {
    const page = loggedInAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    // Backend section heading
    await expect(page.locator('text=Backend')).toBeVisible({ timeout: 10000 });

    // Backend version should be visible
    const backendVersionItems = page.locator('app-metadata-item').filter({ hasText: /^Version/ });
    // There are two Version fields (frontend + backend)
    await expect(backendVersionItems).toHaveCount(2);
  });

  test('should display database version', async ({ loggedInAdminPage }) => {
    const page = loggedInAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    const dbItem = page.locator('app-metadata-item').filter({ hasText: /^Database/ });
    await expect(dbItem).toBeVisible({ timeout: 10000 });
    const dbText = await dbItem.textContent();
    expect(dbText?.replace('Database', '').trim().length).toBeGreaterThan(0);
  });

  test('should show admin diagnostics button for admin users', async ({ loggedInAdminPage }) => {
    const page = loggedInAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    await expect(page.locator('text=You have administrative privileges')).toBeVisible({ timeout: 10000 });
    await expect(page.locator('button:has-text("View Diagnostics")')).toBeVisible();
  });

  test('frontend and backend versions should both be present', async ({ loggedInAdminPage }) => {
    const page = loggedInAdminPage.page;
    await page.goto('/about');
    await page.waitForLoadState('networkidle');

    // Get all version text content for manual verification
    const allVersionItems = page.locator('app-metadata-item').filter({ hasText: /^Version/ });
    const count = await allVersionItems.count();
    expect(count).toBe(2);

    const versions = await allVersionItems.allTextContents();
    // Log for manual verification during testing
    console.log('Frontend version:', versions[0]);
    console.log('Backend version:', versions[1]);

    // Both should have actual version strings
    for (const v of versions) {
      expect(v.trim().length).toBeGreaterThan('Version'.length);
    }
  });

});
